import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@mui/joy";
import {TelegramProvider} from "@/components/TelegramProvider";
import {TelegramAuth} from "tma-jwt";

const inter = Inter({subsets: ["latin", "cyrillic"], display: "fallback"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className='min-h-screen dark'>
        <body
            className={`${inter.className} text-[--tg-theme-text-color] bg-[--tg-background-color] w-full min-h-screen`}>
        <TelegramProvider>
            <ThemeProvider>
                <TelegramAuth>
                    {children}
                </TelegramAuth>
            </ThemeProvider>
        </TelegramProvider>
        </body>
        </html>
    );
}
